# numpy get started

In [ ]:
numpy 提供了一种数组类型，高维数组， 提供了数据分析的运算基础（业务表一般就是二维）

In [1]:
import numpy as np

导入numpy库，并查看numpy版本

In [2]:
np.__version__

'1.14.0'

## 一、创建Array

### 1. 使用np.array()由python list创建

In [ ]:
C       数组的概念 ： 数据类型一致的一个连续的内存空间
python  list列表 （C语言说：列表其实就是一个指针数组）,列表不要求数据类型一致

In [ ]:
numpy的数组：同样是一个【有序】的，【相同数据类型】的集合

In [ ]:
[1, 3.14, 'helloworld', student]

参数为列表：
[1, 4, 2, 5, 3]

numpy设计初衷是用于运算的，所以对数据类型进行统一优化

注意：
- numpy默认ndarray的所有元素的类型是相同的
- 如果传进来的列表中包含不同的类型，则统一为同一类型，优先级：str>float>int

In [3]:
[1,3.14, 'hello']

[1, 3.14, 'hello']

In [9]:
# numpy的数组
array = np.array([1])

In [10]:
array

array([1])

In [8]:
array

array([1.  , 3.14])

In [6]:
array

array(['1', '3.14', 'hello'], dtype='<U32')

In [ ]:
nd.array
np.array

In [15]:
import numpy as np

In [13]:
names = ["tom","lucy","jack"]

array1 = np.array(names)

array1

array(['tom', 'lucy', 'jack'], dtype='<U4')

In [14]:
scores = [1.2, 3.4, 5.6]
array2 = np.array(scores)
array2

array([1.2, 3.4, 5.6])

In [18]:
age = [15,16,18]
array3 = np.array(age, dtype=np.float32)
array3

array([15., 16., 18.], dtype=float32)

In [19]:
money = [[1,2,3],[4,5,6]]
np.array(money)

array([[1, 2, 3],
       [4, 5, 6]])

### 2. 使用np的routines函数创建

包含以下常见创建方法：

1) np.ones(shape, dtype=None, order='C')

In [ ]:
shape = (m,n)  m行n列  二维数组
shape = (m)    m个元素的一维数组  [1,2,3]
shape = (m,)   m个元素的一维数组

shape = (m, 1) m行1列  二维数组   [[1],[2],[3]]
shape = (1, n) 1行m列  二维数组   [[1,2,3]]

In [21]:
# 构造一个5行3列的二维数组
np.ones(shape=(5,3), dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [23]:
# 构造长度为3的一维数组
# np.ones(shape=(3,))
np.ones(shape=(3))

array([1., 1., 1.])

In [24]:
# 构造一个5行1列的二维数组
np.ones(shape=(5,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [27]:
# 构造1行3列的二维数组
np.ones(shape=(1,3))

array([[1., 1., 1.]])

2) np.zeros(shape, dtype=float, order='C')

In [29]:
np.zeros(shape=(5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
np.zeros(shape=(5))

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros(shape=(5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.zeros(shape=(2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

3) np.full(shape, fill_value, dtype=None, order='C')

In [35]:
np.full(shape=(2,3), fill_value=6)

array([[6, 6, 6],
       [6, 6, 6]])

4) np.eye(N, M=None, k=0, dtype=float)  
对角线为1其他的位置为0

In [36]:
# 单位矩阵  l2正则项 

# 生成一个3阶单位矩阵（矩阵除法）
np.eye(N=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(N=5, M=4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [39]:
np.eye(N=5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

5) np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [43]:
# 等差数列
np.linspace(0,10,10, endpoint=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

6) np.arange([start, ]stop, [step, ]dtype=None)

In [44]:
np.arange(0,10,step=1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

7) np.random.randint(low, high=None, size=None, dtype='l')

In [45]:
# size 同 shape
np.random.randint(0,100,size=(5,5))

array([[12,  1, 96, 24, 46],
       [41, 12, 52, 51,  7],
       [54, 31, 32, 45, 42],
       [25, 99, 53, 28, 58],
       [35,  1, 58, 26, 82]])

8) 正态分布函数
- np.random.randn(d0, d1, ..., dn)  标准正态分布　
- np.random.normal()  普通正态分布

In [47]:
np.random.randn(3,5)

array([[-5.92737894e-01,  9.98651958e-04,  9.83879017e-02,
         7.47946088e-01,  1.02224320e+00],
       [-5.20981403e-02, -5.83784210e-01, -6.70960739e-01,
        -8.65926193e-01,  1.26906302e+00],
       [-5.36667903e-01, -8.87429390e-01, -9.86336913e-02,
         5.47045470e-01, -6.55205415e-01]])

In [56]:
np.random.normal(loc=170, scale=5, size=(5,3))

array([[170.45277525, 167.15082355, 166.82556058],
       [183.25651141, 177.1394221 , 163.33401844],
       [176.6030689 , 175.42564751, 174.58575329],
       [185.63263788, 172.07081631, 173.71076065],
       [177.54739458, 171.00039137, 171.12266066]])

9) np.random.random(size=None)  

生成0到1的随机数，左闭右开

In [58]:
np.random.random(size=(5,5))

array([[0.46859088, 0.1085553 , 0.93879923, 0.35422088, 0.50986294],
       [0.86521737, 0.62450588, 0.17819711, 0.34862384, 0.08447991],
       [0.64475435, 0.6912476 , 0.86380419, 0.61470725, 0.21883569],
       [0.30878131, 0.06233349, 0.84309563, 0.48786086, 0.94082987],
       [0.14101842, 0.731601  , 0.42972761, 0.48000133, 0.96594175]])

In [61]:
# 生成一组随机索引
np.random.permutation(10)

array([3, 6, 0, 4, 9, 2, 7, 1, 5, 8])

## 二、ndarray的属性

4个必记参数：

- ndim：维度
- shape：形状（各维度的长度）
- size：总长度
- dtype：元素类型


In [62]:
arr = np.random.randint(0,100,size=(5,4,3))

In [63]:
arr.ndim

3

In [64]:
arr.shape

(5, 4, 3)

In [65]:
arr.size

60

In [66]:
# 获取数组元素类型
arr.dtype

dtype('int32')

In [67]:
# 获取数组类型
type(arr)

numpy.ndarray

创建
属性
如何访问
如何计算

## 三、ndarray的基本操作

In [70]:
data = [[1,2,3],[4,5,6]]

In [71]:
data[0]

[1, 2, 3]

In [72]:
data[0][0]

1

### 1. 索引
一维与列表完全一致
多维时同理

In [73]:
arr1 = np.array([1,2,3,4,5]) 

In [74]:
arr1[0]

1

In [75]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
# 列表的访问方式
arr2[0][0]

1

In [77]:
# numpy特有的
# arr[m,n...] 描述的是对应维度的索引值
arr2[0,0]

1

In [78]:
arr2[1,2]

6

In [79]:
# 高级用法
arr1

array([1, 2, 3, 4, 5])

In [83]:
# 1. 使用列表作为索引访问
arr1[[0,1,2,0,1,2]]

array([1, 2, 3, 1, 2, 3])

In [84]:
# 2. 使用BOOL列表作为索引访问, True对应的值会被返回
bool_list = [True, False, True, False, True]
arr1[bool_list]

array([1, 3, 5])

In [87]:
# eg.获取数组中大于5的数
arr1[arr1 > 3]

array([4, 5])

In [88]:
arr3 = np.random.randint(0,10,size=(5,4,3))
arr3

array([[[9, 4, 0],
        [3, 1, 7],
        [9, 9, 2],
        [0, 2, 6]],

       [[3, 1, 6],
        [1, 0, 1],
        [5, 5, 8],
        [5, 5, 6]],

       [[4, 7, 3],
        [9, 0, 0],
        [4, 0, 4],
        [9, 5, 8]],

       [[0, 8, 1],
        [7, 9, 2],
        [4, 3, 7],
        [7, 0, 3]],

       [[4, 4, 9],
        [1, 7, 4],
        [2, 5, 7],
        [2, 1, 3]]])

In [90]:
arr3[2,0]

array([4, 7, 3])

In [93]:
arr3[0,1,2]

7

In [94]:
# 赋值和访问没有区别，都可以使用

### 2. 切片
一维与列表完全一致
多维时同理

In [97]:
# 所有的切片方式都是开区间（左闭右开）
arr1[0:3]

array([1, 2, 3])

In [99]:
arr2 = np.random.randint(0,100,size=(5,6))
arr2

array([[81, 65, 14, 95, 20, 59],
       [83, 31, 38, 31, 84,  4],
       [36, 66, 32, 75, 77,  8],
       [ 0, 91, 44,  2, 86, 73],
       [69, 36, 20,  4, 92, 40]])

In [100]:
# 行切片
arr2[0:2]

array([[81, 65, 14, 95, 20, 59],
       [83, 31, 38, 31, 84,  4]])

In [101]:
# 列切片 不论多少维，每一个维度的切片范围都是用冒号表示，使用逗号分割，最后一个维度可以省略，但是被切片的维度之前的维度不能省
arr2[:,0:2]

array([[81, 65],
       [83, 31],
       [36, 66],
       [ 0, 91],
       [69, 36]])

In [102]:
arr3 = np.random.randint(0,10,size=(3,4,5))
arr3

array([[[6, 9, 4, 7, 7],
        [9, 6, 5, 0, 0],
        [8, 2, 1, 6, 8],
        [4, 4, 4, 3, 0]],

       [[1, 0, 5, 2, 7],
        [9, 8, 2, 4, 7],
        [2, 7, 5, 6, 8],
        [0, 8, 4, 3, 3]],

       [[0, 9, 7, 2, 0],
        [6, 5, 0, 8, 2],
        [2, 9, 3, 6, 1],
        [8, 9, 2, 3, 0]]])

In [103]:
# 切前两个数组
arr3[0:2]

array([[[6, 9, 4, 7, 7],
        [9, 6, 5, 0, 0],
        [8, 2, 1, 6, 8],
        [4, 4, 4, 3, 0]],

       [[1, 0, 5, 2, 7],
        [9, 8, 2, 4, 7],
        [2, 7, 5, 6, 8],
        [0, 8, 4, 3, 3]]])

In [105]:
# 切割每一个二维数组的前两列
arr3[:,:,0:2]

array([[[6, 9],
        [9, 6],
        [8, 2],
        [4, 4]],

       [[1, 0],
        [9, 8],
        [2, 7],
        [0, 8]],

       [[0, 9],
        [6, 5],
        [2, 9],
        [8, 9]]])

In [107]:
# 切割每一个二维数组的前两行
arr3[:,0:2]

array([[[6, 9, 4, 7, 7],
        [9, 6, 5, 0, 0]],

       [[1, 0, 5, 2, 7],
        [9, 8, 2, 4, 7]],

       [[0, 9, 7, 2, 0],
        [6, 5, 0, 8, 2]]])

将数据反转，例如[1,2,3]---->[3,2,1]

In [109]:
arr1[::-1]

array([5, 4, 3, 2, 1])

In [112]:
arr2

array([[81, 65, 14, 95, 20, 59],
       [83, 31, 38, 31, 84,  4],
       [36, 66, 32, 75, 77,  8],
       [ 0, 91, 44,  2, 86, 73],
       [69, 36, 20,  4, 92, 40]])

In [111]:
arr2[::-1]

array([[69, 36, 20,  4, 92, 40],
       [ 0, 91, 44,  2, 86, 73],
       [36, 66, 32, 75, 77,  8],
       [83, 31, 38, 31, 84,  4],
       [81, 65, 14, 95, 20, 59]])

In [113]:
arr2[:,::-1]

array([[59, 20, 95, 14, 65, 81],
       [ 4, 84, 31, 38, 31, 83],
       [ 8, 77, 75, 32, 66, 36],
       [73, 86,  2, 44, 91,  0],
       [40, 92,  4, 20, 36, 69]])

两个：：进行切片

### 3. 变形
使用reshape函数，注意参数是一个tuple！

In [114]:
arr = np.random.randint(0,10,size=(20))
arr

array([0, 8, 0, 0, 6, 0, 8, 0, 4, 5, 1, 8, 0, 3, 9, 4, 5, 3, 0, 7])

In [119]:
arr.reshape((4,5))

array([[0, 8, 0, 0, 6],
       [0, 8, 0, 4, 5],
       [1, 8, 0, 3, 9],
       [4, 5, 3, 0, 7]])

In [117]:
arr.reshape(3,7)

ValueError: cannot reshape array of size 20 into shape (3,7)

### 4. 级联
1. np.concatenate()
级联需要注意的点：
- 级联的参数是列表：一定要加中括号或小括号
- 维度必须相同
- 形状相符
- 【重点】级联的方向默认是shape这个tuple的第一个值所代表的维度方向
- 可通过axis参数改变级联的方向

In [122]:
arr1 = np.random.randint(0,10,size=(3,3))
arr2 = np.random.randint(10,20,size=(3,3))

display(arr1, arr2)

array([[8, 1, 8],
       [3, 4, 8],
       [5, 5, 7]])

array([[14, 11, 17],
       [16, 17, 10],
       [16, 17, 14]])

In [125]:
# 使用axis控制连接方向，axis指的是连接的维度
# axis 注意轴 非常常见
np.concatenate((arr1, arr2), axis=1)

array([[ 8,  1,  8, 14, 11, 17],
       [ 3,  4,  8, 16, 17, 10],
       [ 5,  5,  7, 16, 17, 14]])

2. np.hstack与np.vstack  
水平级联与垂直级联,处理自己，进行维度的变更

In [126]:
# horizontal
np.hstack((arr1, arr2))

array([[ 8,  1,  8, 14, 11, 17],
       [ 3,  4,  8, 16, 17, 10],
       [ 5,  5,  7, 16, 17, 14]])

In [127]:
# vertical
np.vstack((arr1, arr2))

array([[ 8,  1,  8],
       [ 3,  4,  8],
       [ 5,  5,  7],
       [14, 11, 17],
       [16, 17, 10],
       [16, 17, 14]])

【注意】:级联的时候
         如果是横向级联，参与级联的数组的行数要一致
         纵向级联，参与级联的数组的列数要一致
         如果是高维数组的级联，级联的维度的数据个数要一致

### 5. 切分

与级联类似，三个函数完成切分工作：
- np.split
- np.vsplit
- np.hsplit

In [129]:
arr = np.random.randint(0,100,size=(6,6))
arr

array([[99, 58, 80,  1,  0,  7],
       [87,  4, 12, 78, 27,  6],
       [47,  2, 79, 94, 45, 57],
       [81, 43,  1, 18, 64, 93],
       [79, 61, 77, 67, 37, 25],
       [20, 82, 80, 33, 10, 41]])

In [131]:
# 直接指定切分的份数
part1, part2 = np.split(arr, indices_or_sections=2)
display(part1, part2)

array([[99, 58, 80,  1,  0,  7],
       [87,  4, 12, 78, 27,  6],
       [47,  2, 79, 94, 45, 57]])

array([[81, 43,  1, 18, 64, 93],
       [79, 61, 77, 67, 37, 25],
       [20, 82, 80, 33, 10, 41]])

In [136]:
# 使用axis控制切分方向
part1, part2, part3 = np.split(arr, indices_or_sections=3, axis=1)
display(part1, part2, part3)

array([[99, 58],
       [87,  4],
       [47,  2],
       [81, 43],
       [79, 61],
       [20, 82]])

array([[80,  1],
       [12, 78],
       [79, 94],
       [ 1, 18],
       [77, 67],
       [80, 33]])

array([[ 0,  7],
       [27,  6],
       [45, 57],
       [64, 93],
       [37, 25],
       [10, 41]])

In [137]:
arr2 = np.random.randint(0,100,size=(3,7))
arr2

array([[20, 58, 35,  4, 36, 66, 79],
       [60, 41, 50, 39, 23, 51, 91],
       [ 7, 74, 28, 37, 35, 15, 69]])

In [140]:
# indices_or_sections=[m,n] 表示的范围是0:m, m:n, n:
part1, part2, part3 = np.split(arr2, indices_or_sections=[2,5], axis=1)
display(part1, part2, part3)

array([[20, 58],
       [60, 41],
       [ 7, 74]])

array([[35,  4, 36],
       [50, 39, 23],
       [28, 37, 35]])

array([[66, 79],
       [51, 91],
       [15, 69]])

In [142]:
np.hsplit(arr2, indices_or_sections=[2,5])

[array([[20, 58],
        [60, 41],
        [ 7, 74]]), array([[35,  4, 36],
        [50, 39, 23],
        [28, 37, 35]]), array([[66, 79],
        [51, 91],
        [15, 69]])]

### 6. 副本
所有赋值运算不会为ndarray的任何元素创建副本。对赋值后的对象的操作也对原来的对象生效。

可使用copy()函数创建副本

In [145]:
copy_array = arr.copy()

In [147]:
arr

array([[99, 58, 80,  1,  0,  7],
       [87,  4, 12, 78, 27,  6],
       [47,  2, 79, 94, 45, 57],
       [81, 43,  1, 18, 64, 93],
       [79, 61, 77, 67, 37, 25],
       [20, 82, 80, 33, 10, 41]])

In [148]:
copy_array[0,0] = 1000

In [149]:
arr

array([[99, 58, 80,  1,  0,  7],
       [87,  4, 12, 78, 27,  6],
       [47,  2, 79, 94, 45, 57],
       [81, 43,  1, 18, 64, 93],
       [79, 61, 77, 67, 37, 25],
       [20, 82, 80, 33, 10, 41]])

In [150]:
copy_array

array([[1000,   58,   80,    1,    0,    7],
       [  87,    4,   12,   78,   27,    6],
       [  47,    2,   79,   94,   45,   57],
       [  81,   43,    1,   18,   64,   93],
       [  79,   61,   77,   67,   37,   25],
       [  20,   82,   80,   33,   10,   41]])

## 四、ndarray的聚合操作

In [151]:
arr

array([[99, 58, 80,  1,  0,  7],
       [87,  4, 12, 78, 27,  6],
       [47,  2, 79, 94, 45, 57],
       [81, 43,  1, 18, 64, 93],
       [79, 61, 77, 67, 37, 25],
       [20, 82, 80, 33, 10, 41]])

### 1. 求和np.sum

In [152]:
arr = np.random.randint(0,10,size=10)
arr

array([9, 1, 2, 0, 6, 7, 4, 8, 1, 7])

In [153]:
arr.sum()

45

In [154]:
# 求平均值
arr.mean()

4.5

In [155]:
arr.max()

9

In [156]:
arr.min()

0

In [158]:
# 求最大值索引
arr.argmax()

0

In [160]:
arr

array([9, 1, 2, 0, 6, 7, 4, 8, 1, 7])

In [159]:
arr.argmin()

3

In [161]:
# 标准方差
arr.std()

3.138470965295043

In [162]:
# 求方差
arr.var()

9.85

In [164]:
arr

array([9, 1, 2, 0, 6, 7, 4, 8, 1, 7])

In [163]:
# 注意这个语法格式
np.median(arr)

5.0

In [165]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [170]:
data = np.arange(0,11,step=1)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [172]:
# 第一个参数是要求百分位数的数据
# 第二个参数是要求的百分位的位置
# 异常值检测会使用Q1 Q3 
np.percentile(data, [0.25, 0.75])

array([0.025, 0.075])

In [ ]:
平均值 (d1 + d2 + d3 + ... dn)/n
中位数  
方差  (d1-mean)**2 + (d2-mean)**2 + .. + (dn-mean)**2/n
标注差  sqrt(方差)

In [ ]:
# any  检测一个BOOL数组中，是否至少存在一个True
# all  检测一个BOOL数组中，是否全为True

In [180]:
bool_list = np.array([False, True, False, False])
bool_list.any()

True

In [179]:
bool_list = np.array([True, True, True, True])
bool_list.all()

True

In [181]:
a = 10

In [182]:
a > 10

False

In [183]:
# 找出一组数据中，所有大于该组数据平均值的值
arr

array([9, 1, 2, 0, 6, 7, 4, 8, 1, 7])

In [187]:
# 广播运算， 支持一个numpy.arry和任意一个数运算
condition = arr > arr.mean()
condition

array([ True, False, False, False,  True,  True, False,  True, False,
        True])

In [188]:
arr[condition]

array([9, 6, 7, 8, 7])

In [191]:
# 查看一个数组中，是否存在至少一个大于10的数
(arr > 10).any()

False

### 2. 最大最小值：np.max/ np.min
同理

any()  有True返回True


all()  有False返回False

### 3. 其他聚合操作
    Function Name	NaN-safe Version	Description
    np.sum	np.nansum	Compute sum of elements
    np.prod	np.nanprod	Compute product of elements
    np.mean	np.nanmean	Compute mean of elements
    np.std	np.nanstd	Compute standard deviation
    np.var	np.nanvar	Compute variance
    np.min	np.nanmin	Find minimum value
    np.max	np.nanmax	Find maximum value
    np.argmin	np.nanargmin	Find index of minimum value
    np.argmax	np.nanargmax	Find index of maximum value
    np.median	np.nanmedian	Compute median of elements
    np.percentile	np.nanpercentile	Compute rank-based statistics of elements
    np.any	N/A	Evaluate whether any elements are true
    np.all	N/A	Evaluate whether all elements are true
    np.power 幂运算

np.sum 和 np.nansum 的区别
nan not a number

## 五、ndarray的矩阵操作

### 1. 基本矩阵操作

1) 算术运算符：
- 加减乘除

2) 矩阵积np.dot()

In [206]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,1],[2,2]])
display(a, b)

array([[1, 2],
       [3, 4]])

array([[1, 1],
       [2, 2]])

In [207]:
# 使用符号是对应位置相乘
a * b

array([[1, 2],
       [6, 8]])

In [208]:
# 如果希望做数学中的矩阵运算
np.dot(a, b)

array([[ 5,  5],
       [11, 11]])

### 2. 广播机制

In [192]:
arr

array([9, 1, 2, 0, 6, 7, 4, 8, 1, 7])

In [193]:
3 3 3 3 3 3 3 3 3 3 3

3

In [194]:
arr = np.array([1,2,3,4,5])
data = 3

In [195]:
arr + data

array([4, 5, 6, 7, 8])

【重要】ndarray广播机制的两条规则
- 规则一：为缺失的维度补1
- 规则二：假定缺失元素用已有值填充


例1：
m = np.ones((2, 3))
a = np.arange(3)
求M+a

In [199]:
m = np.ones((2,3))
a = np.arange(3)
display(m, a)

array([[1., 1., 1.],
       [1., 1., 1.]])

array([0, 1, 2])

In [200]:
m + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [201]:
m + 3

array([[4., 4., 4.],
       [4., 4., 4.]])

In [202]:
# 不能广播运算的例子
m = np.ones(shape=(3,3))
n = np.array([[1,2],[3,4]])
display(m, n)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([[1, 2],
       [3, 4]])

In [203]:
m + n

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

例2：
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
求a+b

In [204]:
a = np.arange(0,3,step=1).reshape((3, 1))
b = np.arange(3)
display(a, b)

array([[0],
       [1],
       [2]])

array([0, 1, 2])

In [205]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

习题
a = np.ones((4, 1))
b = np.arange(4)
求a+b

## 六、ndarray的排序

小测验：
使用以上所学numpy的知识，对一个ndarray对象进行冒泡排序。
def bubleSort(x):
代码越短越好

### 1. 快速排序
np.sort()与ndarray.sort()都可以，但有区别：
- np.sort()不改变输入
- ndarray.sort()本地处理，不占用空间，但改变输入

In [212]:
data = np.random.permutation(10)
data

array([0, 5, 4, 8, 3, 7, 2, 6, 1, 9])

In [210]:
data.sort()

In [214]:
data

array([0, 5, 4, 8, 3, 7, 2, 6, 1, 9])

In [213]:
np.sort(data)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2. 部分排序
np.partition(a,k)

有的时候我们不是对全部数据感兴趣，我们可能只对最小或最大的一部分感兴趣。
- 当k为正时，我们想要得到最小的k个数
- 当k为负时，我们想要得到最大的k个数

In [216]:
data = np.random.permutation(10000)
data

array([2564, 9553, 7047, ..., 9020, 8062, 2252])

In [218]:
np.partition(data, 4)[:4]

array([3, 0, 1, 2])

In [222]:
np.partition(data,-4)[-4:]

array([9996, 9997, 9998, 9999])